spring:
  application:
    name: OrderMicroservice
  datasource:
    url: jdbc:postgresql://localhost:5432/Orders
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true
server:
  port: 8081